services:
  webapi-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5439:80" 
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
#docker-compose -f docker-compose.dev.yml up --build
